---
- hosts: all
  vars:
    target_user: "vagrant"
    packages: [ 'git', 'python36', 'redhat-lsb-core', 'cmake', 'python36-devel', 'gcc', 'gcc-c++']
    python_packages: "pynvim jedi"
  tasks:
    - name: update the system
      yum:
        name: '*'
        state: latest

    - name: Install additional software
      yum:
        name: "{{packages}}"
        state: latest

    - name: Install python modules
      command: "sudo /usr/bin/pip3 install {{python_packages}}"

    - name: Install epel repository
      yum:
        name: epel-release
        state: present
    - name: Install snapd
      yum:
        name: snapd
        state: present
    - name: Enable classic snap support
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        owner: root
        group: root
        state: link
    - name: start and enable snapd socket
      command: systemctl enable --now snapd.socket

    - name: install neovim (nvim) snap
      snap:
        name: nvim
        channel: beta
        classic: yes
    - name: "Make sure that .config/nvim for {{target_user}} user is setup"
      file:
        path: "/home/{{target_user}}/.config/nvim"
        owner: "{{target_user}}"
        group: "{{target_user}}"
        state: directory
        recurse: yes

    - name: Copy neovim configuration file
      copy:
        src: files/neovim.config.vim
        dest: "/home/{{target_user}}/.config/nvim/init.vim"
        owner: "{{target_user}}"
        group: "{{target_user}}"
        mode: 0664

    - name: Make sure that "/home/{{target_user}}/.config/nvim/site/autoload/" is created
      file:
        path: "/home/{{target_user}}/.local/share/nvim/site/autoload/"
        owner: "{{target_user}}"
        group: "{{target_user}}"
        state: directory
        recurse: yes

    - name: install vim-plug for neovim
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/home/{{target_user}}/.local/share/nvim/site/autoload/plug.vim"

