# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box ="eurolinux-vagrant/centos-8"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
  
  config.vm.provider "libvirt" do |vb|
    vb.memory = "8096"
    vb.cpus = 4
    vb.storage :file, :size => '20G'
  end

end
